ci: fix node 16 builds (#413)

diff --git a/scripts/install-dependencies b/scripts/install-dependencies
--- a/scripts/install-dependencies
+++ b/scripts/install-dependencies
@@ -15,4 +15,11 @@ elif [[ "${svelte_version}" == "3" ]]; then
   npm install --no-save vite@4 vitest@1 @vitest/coverage-v8@1 @sveltejs/vite-plugin-svelte@2 svelte-check@3 svelte@3
 fi
 
-npm ls --depth=0 svelte
+npm dedupe
+installed_version=$(npm ls --depth=0 --parseable  svelte@${svelte_version})
+
+if [[ -z "${installed_version}" ]]; then
+  echo "Error: expected svelte@${svelte_version}"
+  npm ls --depth=0 svelte
+  exit 1
+fi
