ci: use specific dependencies for different Svelte/Node versions (#436)

diff --git a/scripts/install-dependencies b/scripts/install-dependencies
--- a/scripts/install-dependencies
+++ b/scripts/install-dependencies
@@ -2,30 +2,34 @@
 # Install dependencies for a given version of Svelte
 set -euxo pipefail
 
-svelte_version=${1}
-node_version=$(node --version)
+svelte_version="${1-}"
+node_version=$(node --version | sed 's/^v\([0-9]*\).*/\1/')
+env_dir="tests/envs/svelte$svelte_version"
+env_dir_by_node="$env_dir/node$node_version"
 
-rm -rf node_modules
-npm install --no-package-lock
-
-if [[ "${svelte_version}" == "3" ]]; then
-  npm uninstall --no-save vite vitest @vitest/coverage-v8 @sveltejs/vite-plugin-svelte svelte-check svelte
-  npm install --no-save vite@4 vitest@0.x.x @vitest/coverage-v8@0.x.x @sveltejs/vite-plugin-svelte@2 svelte-check@3 svelte@3
-elif [[ "${svelte_version}" == "4" ]]; then
-  npm uninstall --no-save @sveltejs/vite-plugin-svelte svelte
-  npm install --no-save @sveltejs/vite-plugin-svelte@3 svelte@4
+if [[ -d $env_dir_by_node ]]; then
+  env_dir="$env_dir_by_node"
 fi
 
-if [[ "${node_version}" =~ "v16" ]]; then
-  npm uninstall --no-save vite vitest @vitest/coverage-v8 @sveltejs/vite-plugin-svelte
-  npm install --no-save vite@4 vitest@0.x.x @vitest/coverage-v8@0.x.x @sveltejs/vite-plugin-svelte@2
+if [[ "$svelte_version" == "5" ]]; then
+  rm -rf coverage node_modules
+  npm install
+  exit 0
 fi
 
-npm dedupe
-installed_version=$(npm ls --depth=0 --parseable svelte@${svelte_version})
-
-if [[ -z "${installed_version}" ]]; then
-  echo "Error: expected svelte@${svelte_version}"
-  npm ls --depth=0 svelte
+if [[ -z "$svelte_version" ]]; then
+  echo "Invalid usage: missing Svelte version" >&2;
   exit 1
 fi
+
+if [[ ! -d "$env_dir" ]]; then
+  echo "Error: package.json for Svelte $svelte_version, Node $node_version not found" 1>&2
+  exit 2
+fi
+
+rm -rf coverage node_modules "$env_dir/node_modules"
+pushd "$env_dir"
+npm install --no-package-lock --engine-strict
+npm ls "$env_dir" svelte
+popd
+mv "$env_dir/node_modules" .
